// Generated by CoffeeScript 1.6.3
/*
This file is part of the Lockbox package.

Copyright © 2013 Erin Millard

For the full copyright and license information, please view the LICENSE
file that was distributed with this source code.
*/


(function() {
  var Exception;

  module.exports = Exception = (function() {
    function Exception(message, cause) {
      if (cause === void 0) {
        cause = null;
      }
      this._message = message;
      this._cause = cause;
    }

    Exception.prototype.message = function() {
      return this._message;
    };

    Exception.prototype.cause = function() {
      return this._cause;
    };

    Exception.prototype.toString = function() {
      return this.message();
    };

    return Exception;

  })();

}).call(this);
