// Generated by CoffeeScript 1.6.3
/*
This file is part of the Lockbox package.

Copyright © 2013 Erin Millard

For the full copyright and license information, please view the LICENSE
file that was distributed with this source code.
*/


(function() {
  var Exception;

  module.exports = Exception = (function() {
    function Exception(message, cause) {
      this.message = message;
      this.cause = cause;
      if (this.cause === void 0) {
        this.cause = null;
      }
    }

    Exception.prototype.toString = function() {
      return this.message;
    };

    return Exception;

  })();

}).call(this);
