// Generated by CoffeeScript 1.6.3
/*
This file is part of the Lockbox package.

Copyright © 2013 Erin Millard

For the full copyright and license information, please view the LICENSE
file that was distributed with this source code.
*/


(function() {
  var InvalidEncodingException,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  module.exports = InvalidEncodingException = (function(_super) {
    __extends(InvalidEncodingException, _super);

    function InvalidEncodingException(cause) {
      InvalidEncodingException.__super__.constructor.call(this, 'Invalid encoding.', cause);
    }

    return InvalidEncodingException;

  })(Exception);

}).call(this);
