// Generated by CoffeeScript 1.6.3
/*
This file is part of the Lockbox package.

Copyright © 2013 Erin Millard

For the full copyright and license information, please view the LICENSE
file that was distributed with this source code.
*/


(function() {
  var Exception, InvalidPrivateKeyException,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Exception = require('./Exception');

  module.exports = InvalidPrivateKeyException = (function(_super) {
    __extends(InvalidPrivateKeyException, _super);

    function InvalidPrivateKeyException(key, cause) {
      this.key = key;
      InvalidPrivateKeyException.__super__.constructor.call(this, 'The supplied key is not a valid PEM formatted private key.', cause);
    }

    return InvalidPrivateKeyException;

  })(Exception);

}).call(this);
