// Generated by CoffeeScript 1.6.3
/*
This file is part of the Lockbox package.

Copyright © 2013 Erin Millard

For the full copyright and license information, please view the LICENSE
file that was distributed with this source code.
*/


(function() {
  var Exception, ReadException, util,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  util = require('util');

  Exception = require('./Exception');

  module.exports = ReadException = (function(_super) {
    __extends(ReadException, _super);

    function ReadException(path, cause) {
      var message;
      this.path = path;
      message = util.format("Unable to read from '%s'.", this.path);
      ReadException.__super__.constructor.call(this, message, cause);
    }

    return ReadException;

  })(Exception);

}).call(this);
