// Generated by CoffeeScript 1.6.3
/*
This file is part of the Lockbox package.

Copyright © 2013 Erin Millard

For the full copyright and license information, please view the LICENSE
file that was distributed with this source code.
*/


(function() {
  var BoundDecryptionCipher, DecryptionCipher, InvalidPrivateKeyException;

  DecryptionCipher = require('./DecryptionCipher');

  InvalidPrivateKeyException = require('./Exception/InvalidPrivateKeyException');

  module.exports = BoundDecryptionCipher = (function() {
    function BoundDecryptionCipher(key, decryptionCipher, ursa) {
      var error;
      if (decryptionCipher == null) {
        decryptionCipher = new DecryptionCipher;
      }
      if (ursa == null) {
        ursa = require('ursa');
      }
      try {
        ursa.assertPrivateKey(key);
      } catch (_error) {
        error = _error;
        throw new InvalidPrivateKeyException(key, error);
      }
      this._key = key;
      this._decryptionCipher = decryptionCipher;
    }

    BoundDecryptionCipher.prototype.decrypt = function(data) {
      return this._decryptionCipher.decrypt(this._key, data);
    };

    return BoundDecryptionCipher;

  })();

}).call(this);
