// Generated by CoffeeScript 1.6.3
/*
This file is part of the Lockbox package.

Copyright © 2013 Erin Millard

For the full copyright and license information, please view the LICENSE
file that was distributed with this source code.
*/


(function() {
  var BoundEncryptionCipher, EncryptionCipher, InvalidPublicKeyException;

  EncryptionCipher = require('./EncryptionCipher');

  InvalidPublicKeyException = require('./Exception/InvalidPublicKeyException');

  module.exports = BoundEncryptionCipher = (function() {
    function BoundEncryptionCipher(key, encryptionCipher, ursa) {
      var error;
      if (encryptionCipher == null) {
        encryptionCipher = new EncryptionCipher;
      }
      if (ursa == null) {
        ursa = require('ursa');
      }
      try {
        ursa.assertKey(key);
      } catch (_error) {
        error = _error;
        throw new InvalidPublicKeyException(key, error);
      }
      this._key = key;
      this._encryptionCipher = encryptionCipher;
    }

    BoundEncryptionCipher.prototype.encrypt = function(data) {
      return this._encryptionCipher.encrypt(this._key, data);
    };

    return BoundEncryptionCipher;

  })();

}).call(this);
