// Generated by CoffeeScript 1.6.3
/*
This file is part of the Lockbox package.

Copyright © 2013 Erin Millard

For the full copyright and license information, please view the LICENSE
file that was distributed with this source code.
*/


(function() {
  var Cipher, DecryptionCipher, EncryptionCipher;

  DecryptionCipher = require('./DecryptionCipher');

  EncryptionCipher = require('./EncryptionCipher');

  module.exports = Cipher = (function() {
    function Cipher(encryptionCipher, decryptionCipher) {
      if (encryptionCipher == null) {
        encryptionCipher = new EncryptionCipher;
      }
      if (decryptionCipher == null) {
        decryptionCipher = new DecryptionCipher;
      }
      this._encryptionCipher = encryptionCipher;
      this._decryptionCipher = decryptionCipher;
    }

    Cipher.prototype.encrypt = function(key, data) {
      return this._encryptionCipher.encrypt(key, data);
    };

    Cipher.prototype.decrypt = function(key, data) {
      return this._decryptionCipher.decrypt(key, data);
    };

    return Cipher;

  })();

}).call(this);
