// Generated by CoffeeScript 1.6.3
/*
This file is part of the Lockbox package.

Copyright © 2013 Erin Millard

For the full copyright and license information, please view the LICENSE
file that was distributed with this source code.
*/


(function() {
  var KeyFactory;

  module.exports = KeyFactory = (function() {
    function KeyFactory(ursa, fs) {
      if (ursa == null) {
        ursa = require('ursa');
      }
      if (fs == null) {
        fs = require('fs');
      }
      this._ursa = ursa;
      this._fs = fs;
    }

    KeyFactory.prototype.createPrivateKey = function(key, password) {
      if (!password) {
        password = void 0;
      }
      return this._ursa.createPrivateKey(key, password);
    };

    KeyFactory.prototype.createPublicKey = function(key) {
      return this._ursa.createPublicKey(key);
    };

    KeyFactory.prototype.createPrivateKeyFromFile = function(path, password, callback) {
      var _this = this;
      return this._fs.readFile(path, {}, function(error, key) {
        if (error) {
          return callback(error);
        }
        return callback(null, _this.createPrivateKey(key, password));
      });
    };

    KeyFactory.prototype.createPrivateKeyFromFileSync = function(path, password, callback) {
      var key;
      key = this._fs.readFileSync(path);
      return this.createPrivateKey(key, password);
    };

    KeyFactory.prototype.createPublicKeyFromFile = function(path, callback) {
      var _this = this;
      return this._fs.readFile(path, {}, function(error, key) {
        if (error) {
          return callback(error);
        }
        return callback(null, _this.createPublicKey(key));
      });
    };

    KeyFactory.prototype.createPublicKeyFromFileSync = function(path, callback) {
      return this.createPublicKey(this._fs.readFileSync(path));
    };

    return KeyFactory;

  })();

}).call(this);
