// Generated by CoffeeScript 1.6.3
/*
This file is part of the Lockbox package.

Copyright © 2013 Erin Millard

For the full copyright and license information, please view the LICENSE
file that was distributed with this source code.
*/


(function() {
  var BoundCipher, BoundDecryptionCipher, BoundEncryptionCipher, Cipher, DecryptionCipher, DecryptionFailedException, EncryptionCipher, InvalidPrivateKeyException, InvalidPublicKeyException, KeyFactory, ReadException, decryptionCipher, encryptionCipher, keyFactory;

  BoundCipher = require('./BoundCipher');

  BoundDecryptionCipher = require('./BoundDecryptionCipher');

  BoundEncryptionCipher = require('./BoundEncryptionCipher');

  Cipher = require('./Cipher');

  DecryptionCipher = require('./DecryptionCipher');

  EncryptionCipher = require('./EncryptionCipher');

  KeyFactory = require('./KeyFactory');

  DecryptionFailedException = require('./Exception/DecryptionFailedException');

  InvalidPrivateKeyException = require('./Exception/InvalidPrivateKeyException');

  InvalidPublicKeyException = require('./Exception/InvalidPublicKeyException');

  ReadException = require('./Exception/ReadException');

  encryptionCipher = new EncryptionCipher;

  decryptionCipher = new DecryptionCipher;

  keyFactory = new KeyFactory;

  module.exports = {
    BoundCipher: BoundCipher,
    BoundDecryptionCipher: BoundDecryptionCipher,
    BoundEncryptionCipher: BoundEncryptionCipher,
    Cipher: Cipher,
    DecryptionCipher: DecryptionCipher,
    EncryptionCipher: EncryptionCipher,
    KeyFactory: KeyFactory,
    exception: {
      DecryptionFailedException: DecryptionFailedException,
      InvalidPrivateKeyException: InvalidPrivateKeyException,
      InvalidPublicKeyException: InvalidPublicKeyException,
      ReadException: ReadException
    },
    keyFactory: keyFactory,
    encrypt: function(key, data) {
      return encryptionCipher.encrypt(key, data);
    },
    decrypt: function(key, data) {
      return decryptionCipher.decrypt(key, data);
    }
  };

}).call(this);
